In [1]:
import numpy as np


In [3]:
np.random.seed(55)
a=np.random.randint(30,99,20)
a

array([56, 69, 59, 91, 85, 67, 63, 84, 65, 76, 91, 42, 54, 61, 81, 30, 85,
       92, 73, 79])

In [12]:
b=np.random.randint(20,80,(8,9))
b

array([[44, 68, 34, 76, 30, 79, 79, 48, 61],
       [64, 44, 72, 49, 64, 41, 33, 72, 61],
       [78, 53, 65, 44, 38, 36, 65, 75, 47],
       [38, 76, 62, 52, 73, 30, 74, 23, 44],
       [78, 27, 38, 21, 39, 65, 73, 50, 39],
       [30, 45, 22, 44, 52, 33, 55, 31, 54],
       [35, 53, 62, 54, 68, 79, 41, 40, 23],
       [27, 40, 33, 54, 36, 60, 39, 46, 34]])

In [16]:
b.shape

(8, 9)

In [18]:
b[1:5,1:6]


array([[44, 72, 49, 64, 41],
       [53, 65, 44, 38, 36],
       [76, 62, 52, 73, 30],
       [27, 38, 21, 39, 65]])

In [22]:
b[7,0]


27

In [24]:
import pandas  as  pd

In [28]:
k=[4,7,2,9,7,3,90,50,]
k

[4, 7, 2, 9, 7, 3, 90, 50]

In [30]:
np.array(k)


array([ 4,  7,  2,  9,  7,  3, 90, 50])

In [34]:
pd.Series(k)


0     4
1     7
2     2
3     9
4     7
5     3
6    90
7    50
dtype: int64

In [38]:
k=[[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [42]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [44]:
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [48]:
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [52]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50